version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: tegbe-postgres-local
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: tegbedb
    ports:
      - "5432:5432"
    volumes:
      - tegbe_pgdata:/var/lib/postgresql/data

volumes:
  tegbe_pgdata: